# Generated by Django 3.2.3 on 2023-03-16 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_detail',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('LOGIN_ISSUE', 'LOGIN_ISSUE'), ('BANNED', 'BANNED')], default='ACTIVE', max_length=255),
        ),
    ]
